name: License Header Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-license-header:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Headers
        uses: apache/skywalking-eyes/header@v0.8.0
