name: License Header Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, 'release-*']

jobs:
  check-license-header:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Headers
        uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
